#Headless browser option
browser:
  webkit: "phantomjs"
  # gecko: "slimerjs"

device:
  base: firefox
  compare: firefox

#If you want to have multiple snapping files, set the file name here
snap_file: "snap.js"

# Type the name of the directory that shots will be stored in
directory:
  - 'shots'

# Add only 2 domains, key will act as a label
domains:
  prod: "http://sbelyea.net"
  localhost: "http://localhost:4000"

#Type screen widths below, here are a couple of examples
screen_widths:
  - 320
  - 480
  - 600
  - 768
  - 1024
  - 1280

#Type page URL paths below, here are a couple of examples
#paths:
#  home: "/"
#  articles: "/articles/working-with-wraith/"

# If you don't want to name the paths explicitly you can use a yaml
# collection as follows, and names will be derived by replacing / with _
#
# paths:
#  - /imghp
#  - /maps

#Amount of fuzz ImageMagick will use 
fuzz: '20%'  

#Set the number of days to keep the site spider file
spider_days:
  - 10